const bcryptNative = require('bcrypt');
const bcryptJS = require('bcryptjs');

async function test() {
    const password = 'testpassword';
    const saltJS = await bcryptJS.genSalt(10);
    const hashJS = await bcryptJS.hash(password, saltJS);
    
    console.log('Hash generated by bcryptjs:', hashJS);
    
    const matchNative = await bcryptNative.compare(password, hashJS);
    console.log('Match with native bcrypt:', matchNative);
    
    const saltNative = await bcryptNative.genSalt(10);
    const hashNative = await bcryptNative.hash(password, saltNative);
    console.log('Hash generated by native bcrypt:', hashNative);
    
    const matchJS = await bcryptJS.compare(password, hashNative);
    console.log('Match with bcryptjs:', matchJS);
}

test();
