export enum SexEnum {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  UNKNOW = 'UNKNOW',
}

export enum AccessEnum {
  CAN_CREATE_USER = 'CAN_CREATE_USER',
  CAN_UPDATE_USER = 'CAN_UPDATE_USER',
  CAN_DELETE_USER = 'CAN_DELETE_USER',
  CAN_SHOW_USER = 'CAN_SHOW_USER',
  CAN_SET_USER_STATE = 'CAN_SET_USER_STATE',
  CAN_SHOW_USER_LIST = 'CAN_SHOW_USER_LIST',
}

export enum AccountRole {
  SUPER_ADMIN = 'SUPER ADMIN',
  ADMIN = 'ADMIN',
  USER = 'USER',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
}
